#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

sys.path.append("../monolithe")

if __name__ == '__main__':
    from monolithe.generators.specifications.cli import main
    sys.exit(main(sys.argv))
