# -*- coding: utf-8 -*-
"""

NUDSCPForwardingClassMapping
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject



class NUDSCPForwardingClassMapping(NURESTObject):
    """ Represents a DSCPForwardingClassMapping object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUDSCPForwardingClassMapping instance """

        super(NUDSCPForwardingClassMapping, self).__init__()

        # Read/Write Attributes
        self.dscp = None  #  DSCP value range from enumeration of 65 values: *, 0, 1 ... 63 - int
        self.forwarding_class = None  #  Class of service to be used. Service classes in order of priority are A, B, C, D, E, F, G and H - int
        
        self.expose_attribute(local_name=u"dscp", remote_name=u"DSCP", attribute_type=int)
        self.expose_attribute(local_name=u"forwarding_class", remote_name=u"forwardingClass", attribute_type=int)
        
        # Fetchers
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"dscpforwardingclassmapping"


