# -*- coding: utf-8 -*-
"""

NUFlowForwardingPolicy
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject



class NUFlowForwardingPolicy(NURESTObject):
    """ Represents a FlowForwardingPolicy object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUFlowForwardingPolicy instance """

        super(NUFlowForwardingPolicy, self).__init__()

        # Read/Write Attributes
        self.redirect_target_id = None  #  The associated service id. - int
        self.type = None  #  The redirect type. - int
        self.associated_network_object_id = None  #  The associated network object id. - int
        self.associated_network_object_type = None  #  The associated network object type. - int
        self.destination_address_overwrite = None  #  The destination address overwrite. - int
        self.flow_id = None  #  The associated service id. - int
        self.associated_application_service_id = None  #  The associated service id. - int
        self.source_address_overwrite = None  #  The source address overwrite. - int
        
        self.expose_attribute(local_name=u"redirect_target_id", remote_name=u"redirectTargetID", attribute_type=int)
        self.expose_attribute(local_name=u"type", remote_name=u"type", attribute_type=int)
        self.expose_attribute(local_name=u"associated_network_object_id", remote_name=u"associatedNetworkObjectID", attribute_type=int)
        self.expose_attribute(local_name=u"associated_network_object_type", remote_name=u"associatedNetworkObjectType", attribute_type=int)
        self.expose_attribute(local_name=u"destination_address_overwrite", remote_name=u"destinationAddressOverwrite", attribute_type=int)
        self.expose_attribute(local_name=u"flow_id", remote_name=u"flowID", attribute_type=int)
        self.expose_attribute(local_name=u"associated_application_service_id", remote_name=u"associatedApplicationServiceID", attribute_type=int)
        self.expose_attribute(local_name=u"source_address_overwrite", remote_name=u"sourceAddressOverwrite", attribute_type=int)
        
        # Fetchers
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"flowforwardingpolicy"


