# -*- coding: utf-8 -*-

"""
NUIngressAdvancedForwardingTemplate
Defines the template for an Ingress Advanced Forwarding

This file has been autogenerated and should not be modified.
Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from ..fetchers import NUIngressAdvancedForwardingTemplateEntriesFetcher
from bambou import NURESTObject


class NUIngressAdvancedForwardingTemplate(NURESTObject):
    """ Represents a IngressAdvancedForwardingTemplate object

        IMPORTANT: This file has been autogenerated. Do not override it !

    """

    def __init__(self, **kwargs):
        """ Initializes a IngressAdvancedForwardingTemplate instance

        """
        super(NUIngressAdvancedForwardingTemplate, self).__init__()

        # Read/Write Attributes
        
        self._active = bool()
        self._description = str()
        self._name = str()
        
        self.expose_attribute(local_name=u"active", remote_name=u"active", attribute_type=bool)
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=str)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=str)
        
        # Fetchers
        
        self.ingressadvfwdentrytemplates = []
        self.ingressadvfwdentrytemplates_fetcher = NUIngressAdvancedForwardingTemplateEntriesFetcher.fetcher_with_entity(entity=self, local_name=u"ingressadvfwdentrytemplates")
        
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)

    # Properties
    
    def _get_active(self):
        """ Get attribute active

            If enabled, it means that this ACL or QOS entry is active

        """
        return self._active

    def _set_active(self, value):
        """ Set attribute active

            If enabled, it means that this ACL or QOS entry is active

        """
        self._active = value

    active = property(_get_active, _set_active)
    
    def _get_description(self):
        """ Get attribute description

            A description of the entity

        """
        return self._description

    def _set_description(self, value):
        """ Set attribute description

            A description of the entity

        """
        self._description = value

    description = property(_get_description, _set_description)
    
    def _get_name(self):
        """ Get attribute name

            The name of the entity

        """
        return self._name

    def _set_name(self, value):
        """ Set attribute name

            The name of the entity

        """
        self._name = value

    name = property(_get_name, _set_name)
    
    # Methods

    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI

        """
        return u"ingressadvfwdtemplate"
