# -*- coding: utf-8 -*-
"""

NUIngressAdvancedForwardingTemplate
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUIngressAdvancedForwardingTemplateEntriesFetcher


class NUIngressAdvancedForwardingTemplate(NURESTObject):
    """ Represents a IngressAdvancedForwardingTemplate object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUIngressAdvancedForwardingTemplate instance """

        super(NUIngressAdvancedForwardingTemplate, self).__init__()

        # Read/Write Attributes
        self.description = None  #  A description of the entity - int
        self.name = None  #  The name of the entity - int
        self.active = None  #  If enabled, it means that this ACL or QOS entry is active - int
        
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=int)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=int)
        self.expose_attribute(local_name=u"active", remote_name=u"active", attribute_type=int)
        
        # Fetchers
        self.ingress_advanced_forwarding_template_entries = []
        self.ingress_advanced_forwarding_template_entries_fetcher = NUIngressAdvancedForwardingTemplateEntriesFetcher.fetcher_with_object(nurest_object=self, local_name=u"ingress_advanced_forwarding_template_entries")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"ingressadvancedforwardingtemplate"


