# -*- coding: utf-8 -*-
"""

NUMetadata
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject



class NUMetadata(NURESTObject):
    """ Represents a Metadata object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUMetadata instance """

        super(NUMetadata, self).__init__()

        # Read/Write Attributes
        self.metadata = None  #  Metadata that describes about the entity attached to it. - int
        self.resource_type = None  #  Type of the resource that is associated to the Metadata. - int
        
        self.expose_attribute(local_name=u"metadata", remote_name=u"metadata", attribute_type=int)
        self.expose_attribute(local_name=u"resource_type", remote_name=u"resourceType", attribute_type=int)
        
        # Fetchers
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"metadata"


