# -*- coding: utf-8 -*-
"""

NUMirrorDestination
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUVPortMirrorsFetcher


class NUMirrorDestination(NURESTObject):
    """ Represents a MirrorDestination object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUMirrorDestination instance """

        super(NUMirrorDestination, self).__init__()

        # Read/Write Attributes
        self.destination_ip = None  #  IP address of the destination server where you want your traffic to be mirrored. - int
        self.name = None  #  Name of the mirror destination. Valid characters are alphabets, numbers, space and hyphen( - ). - int
        self.service_id = None  #  Service ID of the mirror destination. - long
        
        self.expose_attribute(local_name=u"destination_ip", remote_name=u"destinationIp", attribute_type=int)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=int)
        self.expose_attribute(local_name=u"service_id", remote_name=u"serviceId", attribute_type=long)
        
        # Fetchers
        self.v_port_mirrors = []
        self.v_port_mirrors_fetcher = NUVPortMirrorsFetcher.fetcher_with_object(nurest_object=self, local_name=u"v_port_mirrors")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"mirrordestination"


