# -*- coding: utf-8 -*-

"""
NUMultiCastChannelMap
This is the definition of a MultiCast Channel Map

This file has been autogenerated and should not be modified.
Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from ..fetchers import NUMultiCastRangesFetcher
from bambou import NURESTObject


class NUMultiCastChannelMap(NURESTObject):
    """ Represents a MultiCastChannelMap object

        IMPORTANT: This file has been autogenerated. Do not override it !

    """

    def __init__(self, **kwargs):
        """ Initializes a MultiCastChannelMap instance

        """
        super(NUMultiCastChannelMap, self).__init__()

        # Read/Write Attributes
        
        self._description = str()
        self._name = str()
        
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=str)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=str)
        
        # Fetchers
        
        self.multicastranges = []
        self.multicastranges_fetcher = NUMultiCastRangesFetcher.fetcher_with_entity(entity=self, local_name=u"multicastranges")
        
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)

    # Properties
    
    def _get_description(self):
        """ Get attribute description

            A description field provided by the user that identifies the MultiCast Channel Map

        """
        return self._description

    def _set_description(self, value):
        """ Set attribute description

            A description field provided by the user that identifies the MultiCast Channel Map

        """
        self._description = value

    description = property(_get_description, _set_description)
    
    def _get_name(self):
        """ Get attribute name

            Name of the current entity

        """
        return self._name

    def _set_name(self, value):
        """ Set attribute name

            Name of the current entity

        """
        self._name = value

    name = property(_get_name, _set_name)
    
    # Methods

    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI

        """
        return u"multicastchannelmap"
