# -*- coding: utf-8 -*-

"""
NUNATMapEntry
Defines a MAP between the private ip and public ip

This file has been autogenerated and should not be modified.
Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject


class NUNATMapEntry(NURESTObject):
    """ Represents a NATMapEntry object

        IMPORTANT: This file has been autogenerated. Do not override it !

    """

    def __init__(self, **kwargs):
        """ Initializes a NATMapEntry instance

        """
        super(NUNATMapEntry, self).__init__()

        # Read/Write Attributes
        
        self._public_ip = str()
        self._associated_patnat_pool_id = str()
        self._private_ip = str()
        
        self.expose_attribute(local_name=u"public_ip", remote_name=u"publicIP", attribute_type=str)
        self.expose_attribute(local_name=u"associated_patnat_pool_id", remote_name=u"associatedPATNATPoolID", attribute_type=str)
        self.expose_attribute(local_name=u"private_ip", remote_name=u"privateIP", attribute_type=str)
        
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)

    # Properties
    
    def _get_public_ip(self):
        """ Get attribute public_ip

            Public IP address of the interface

        """
        return self._public_ip

    def _set_public_ip(self, value):
        """ Set attribute public_ip

            Public IP address of the interface

        """
        self._public_ip = value

    public_ip = property(_get_public_ip, _set_public_ip)
    
    def _get_associated_patnat_pool_id(self):
        """ Get attribute associated_patnat_pool_id

            Read Only - Indicates which PATNATPool this entry belongs to

        """
        return self._associated_patnat_pool_id

    def _set_associated_patnat_pool_id(self, value):
        """ Set attribute associated_patnat_pool_id

            Read Only - Indicates which PATNATPool this entry belongs to

        """
        self._associated_patnat_pool_id = value

    associated_patnat_pool_id = property(_get_associated_patnat_pool_id, _set_associated_patnat_pool_id)
    
    def _get_private_ip(self):
        """ Get attribute private_ip

            Private IP address of the interface

        """
        return self._private_ip

    def _set_private_ip(self, value):
        """ Set attribute private_ip

            Private IP address of the interface

        """
        self._private_ip = value

    private_ip = property(_get_private_ip, _set_private_ip)
    
    # Methods

    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI

        """
        return u"natmapentry"
