# -*- coding: utf-8 -*-
"""

NUPATNATPool
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUEnterprisePermissionsFetcher
from ..fetchers import NUNATMapEntriesFetcher


class NUPATNATPool(NURESTObject):
    """ Represents a PATNATPool object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUPATNATPool instance """

        super(NUPATNATPool, self).__init__()

        # Read/Write Attributes
        self.address_range = None  #  Pool of IP Address that is available for use ex : 130.12.0.0/16 - int
        self.associated_gateway_id = None  #   - int
        self.default_patip = None  #  Default PAT IP Address, must belong to the pool above - int
        self.description = None  #  A description of the PATNATPool - int
        self.name = None  #  Name of the PATNATPool - int
        self.permitted_action = None  #  The permitted  action to USE/EXTEND  this Gateway - int
        
        self.expose_attribute(local_name=u"address_range", remote_name=u"addressRange", attribute_type=int)
        self.expose_attribute(local_name=u"associated_gateway_id", remote_name=u"associatedGatewayID", attribute_type=int)
        self.expose_attribute(local_name=u"default_patip", remote_name=u"defaultPATIP", attribute_type=int)
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=int)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=int)
        self.expose_attribute(local_name=u"permitted_action", remote_name=u"permittedAction", attribute_type=int)
        
        # Fetchers
        self.enterprise_permissions = []
        self.enterprise_permissions_fetcher = NUEnterprisePermissionsFetcher.fetcher_with_object(nurest_object=self, local_name=u"enterprise_permissions")
        self.nat_map_entries = []
        self.nat_map_entries_fetcher = NUNATMapEntriesFetcher.fetcher_with_object(nurest_object=self, local_name=u"nat_map_entries")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"patnatpool"


