# -*- coding: utf-8 -*-
"""

NUPort
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUPermittedActionsFetcher
from ..fetchers import NUEnterprisePermissionsFetcher
from ..fetchers import NUVlansFetcher
from ..fetchers import NUEventLogsFetcher
from ..fetchers import NUAlarmsFetcher


class NUPort(NURESTObject):
    """ Represents a Port object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUPort instance """

        super(NUPort, self).__init__()

        # Read/Write Attributes
        self.template_id = None  #  The ID of the template that this Port was created from - int
        self.name = None  #  Name of the Port - int
        self.permitted_action = None  #  The permitted  action to USE/EXTEND  this Gateway - int
        self.physical_name = None  #  Identifier of the Port - int
        self.port_type = None  #  Type of the Port - NETWORK,ACCESS - int
        self.status = None  #  Status of the port. Possible values are - INITIALIZED, ORPHAN, READY, MISMATCH - int
        self.user_mnemonic = None  #  user mnemonic of the Port - int
        self.use_user_mnemonic = None  #  determines whether to use user mnemonic of the Port - int
        self.associated_egress_qos_policy_id = None  #  ID of the Egress QOS Policy associated with this Vlan. - int
        self.description = None  #  A description of the Port - int
        self.infrastructure_profile_id = None  #  The ID of the infrastructure profile this is associated to - int
        self.vlan_range = None  #  VLAN Range of the Port - int
        
        self.expose_attribute(local_name=u"template_id", remote_name=u"templateID", attribute_type=int)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=int)
        self.expose_attribute(local_name=u"permitted_action", remote_name=u"permittedAction", attribute_type=int)
        self.expose_attribute(local_name=u"physical_name", remote_name=u"physicalName", attribute_type=int)
        self.expose_attribute(local_name=u"port_type", remote_name=u"portType", attribute_type=int)
        self.expose_attribute(local_name=u"status", remote_name=u"status", attribute_type=int)
        self.expose_attribute(local_name=u"user_mnemonic", remote_name=u"userMnemonic", attribute_type=int)
        self.expose_attribute(local_name=u"use_user_mnemonic", remote_name=u"useUserMnemonic", attribute_type=int)
        self.expose_attribute(local_name=u"associated_egress_qos_policy_id", remote_name=u"associatedEgressQOSPolicyID", attribute_type=int)
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=int)
        self.expose_attribute(local_name=u"infrastructure_profile_id", remote_name=u"infrastructureProfileID", attribute_type=int)
        self.expose_attribute(local_name=u"vlan_range", remote_name=u"VLANRange", attribute_type=int)
        
        # Fetchers
        self.permitted_actions = []
        self.permitted_actions_fetcher = NUPermittedActionsFetcher.fetcher_with_object(nurest_object=self, local_name=u"permitted_actions")
        self.enterprise_permissions = []
        self.enterprise_permissions_fetcher = NUEnterprisePermissionsFetcher.fetcher_with_object(nurest_object=self, local_name=u"enterprise_permissions")
        self.vlans = []
        self.vlans_fetcher = NUVlansFetcher.fetcher_with_object(nurest_object=self, local_name=u"vlans")
        self.event_logs = []
        self.event_logs_fetcher = NUEventLogsFetcher.fetcher_with_object(nurest_object=self, local_name=u"event_logs")
        self.alarms = []
        self.alarms_fetcher = NUAlarmsFetcher.fetcher_with_object(nurest_object=self, local_name=u"alarms")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"port"


