# -*- coding: utf-8 -*-
"""

NUPolicyDecision
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUQosPrimitivesFetcher


class NUPolicyDecision(NURESTObject):
    """ Represents a PolicyDecision object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUPolicyDecision instance """

        super(NUPolicyDecision, self).__init__()

        # Read/Write Attributes
        self.egress_ac_ls = None  #  List of actual Egress ACLs that will be applied on the interface of this VM - int
        self.egress_qos = None  #  Egress QoS primitive that was selected - int
        self.ingress_ac_ls = None  #  List of actual Ingress ACLs that will be applied on the interface of this VM - int
        self.ingress_adv_fwd = None  #  List of actual Ingress Redirect ACLs that will be applied on the interface of this VM - int
        self.qos = None  #  QoS primitive that was selected based on inheritance policies - int
        self.stats = None  #  Stats primitive that was selected based on inheritance policies - int
        
        self.expose_attribute(local_name=u"egress_ac_ls", remote_name=u"egressACLs", attribute_type=int)
        self.expose_attribute(local_name=u"egress_qos", remote_name=u"egressQos", attribute_type=int)
        self.expose_attribute(local_name=u"ingress_ac_ls", remote_name=u"ingressACLs", attribute_type=int)
        self.expose_attribute(local_name=u"ingress_adv_fwd", remote_name=u"ingressAdvFwd", attribute_type=int)
        self.expose_attribute(local_name=u"qos", remote_name=u"qos", attribute_type=int)
        self.expose_attribute(local_name=u"stats", remote_name=u"stats", attribute_type=int)
        
        # Fetchers
        self.qos_primitives = []
        self.qos_primitives_fetcher = NUQosPrimitivesFetcher.fetcher_with_object(nurest_object=self, local_name=u"qos_primitives")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"policydecision"


