# -*- coding: utf-8 -*-
"""

NURedirectionTarget
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject

from ..fetchers import NUVPortsFetcher
from ..fetchers import NUVirtualIPsFetcher
from ..fetchers import NUEventLogsFetcher


class NURedirectionTarget(NURESTObject):
    """ Represents a RedirectionTarget object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NURedirectionTarget instance """

        super(NURedirectionTarget, self).__init__()

        # Read/Write Attributes
        self.description = None  #  Description of this redirection target - int
        self.end_point_type = None  #  EndpointType defines the type of header rewrite and forwarding performed by VRS when the endpoint is used as a PBR destination. Possible Values - NONE/L3/VIRTUAL_WIRE - int
        self.esi = None  #  ESI id, globally unique - int
        self.name = None  #  Name of this redirection target - int
        self.redundancy_enabled = None  #  Allow/Disallow redundant appliances and VIP - int
        self.template_id = None  #  Template to which this redirection target belongs to - int
        self.trigger_type = None  #  Trigger type, could be - NONE/GARP, THIS IS READ ONLY. - int
        self.virtual_network_id = None  #  Auto Generated by VSD. Each vPortTag with redundancy=enable and EndpointType != none will have a globally unique ESI &amp; VNID generated by VSD - int
        
        self.expose_attribute(local_name=u"description", remote_name=u"description", attribute_type=int)
        self.expose_attribute(local_name=u"end_point_type", remote_name=u"endPointType", attribute_type=int)
        self.expose_attribute(local_name=u"esi", remote_name=u"ESI", attribute_type=int)
        self.expose_attribute(local_name=u"name", remote_name=u"name", attribute_type=int)
        self.expose_attribute(local_name=u"redundancy_enabled", remote_name=u"redundancyEnabled", attribute_type=int)
        self.expose_attribute(local_name=u"template_id", remote_name=u"templateID", attribute_type=int)
        self.expose_attribute(local_name=u"trigger_type", remote_name=u"triggerType", attribute_type=int)
        self.expose_attribute(local_name=u"virtual_network_id", remote_name=u"virtualNetworkID", attribute_type=int)
        
        # Fetchers
        self.v_ports = []
        self.v_ports_fetcher = NUVPortsFetcher.fetcher_with_object(nurest_object=self, local_name=u"v_ports")
        self.virtual_ips = []
        self.virtual_ips_fetcher = NUVirtualIPsFetcher.fetcher_with_object(nurest_object=self, local_name=u"virtual_ips")
        self.event_logs = []
        self.event_logs_fetcher = NUEventLogsFetcher.fetcher_with_object(nurest_object=self, local_name=u"event_logs")
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"redirectiontarget"


