# -*- coding: utf-8 -*-
"""

NUStatsCollectorInfo
This file has been autogenerated by Swagger  and should not be modified.

Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject



class NUStatsCollectorInfo(NURESTObject):
    """ Represents a StatsCollectorInfo object in Nuage VSD solution
        IMPORTANT: Do not override this object.
    """

    def __init__(self, **kwargs):
        """ Initialize a NUStatsCollectorInfo instance """

        super(NUStatsCollectorInfo, self).__init__()

        # Read/Write Attributes
        self.address_type = None  #  Type for stats collector address - int
        self.ip_address = None  #  IP address(es) of the stats collector process - int
        self.port = None  #  Port(s) of the stats collector process - int
        
        self.expose_attribute(local_name=u"address_type", remote_name=u"addressType", attribute_type=int)
        self.expose_attribute(local_name=u"ip_address", remote_name=u"ipAddress", attribute_type=int)
        self.expose_attribute(local_name=u"port", remote_name=u"port", attribute_type=int)
        
        # Fetchers
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)



    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI """

        return u"statscollectorinfo"


