# -*- coding: utf-8 -*-

"""
NUVirtualIP
Virtual IP address

This file has been autogenerated and should not be modified.
Author Christophe Serafin <christophe.serafin@alcatel-lucent.com>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"""

from bambou import NURESTObject


class NUVirtualIP(NURESTObject):
    """ Represents a VirtualIP object

        IMPORTANT: This file has been autogenerated. Do not override it !

    """

    def __init__(self, **kwargs):
        """ Initializes a VirtualIP instance

        """
        super(NUVirtualIP, self).__init__()

        # Read/Write Attributes
        
        self._virtual_ip = str()
        
        self.expose_attribute(local_name=u"virtual_ip", remote_name=u"virtualIP", attribute_type=str)
        
        for key, value in kwargs.iteritems():
            if hasattr(self, key):
                setattr(self, key, value)

    # Properties
    
    def _get_virtual_ip(self):
        """ Get attribute virtual_ip

            Virtual IP address

        """
        return self._virtual_ip

    def _set_virtual_ip(self, value):
        """ Set attribute virtual_ip

            Virtual IP address

        """
        self._virtual_ip = value

    virtual_ip = property(_get_virtual_ip, _set_virtual_ip)
    
    # Methods

    @classmethod
    def get_remote_name(cls):
        """ Remote name that will be used to generates URI

        """
        return u"virtualip"
