# -*- coding: utf-8 -*-

import os
import shutil

from monolithe.tests.functional import FunctionalTest
from monolithe.generators import VSDKGenerator


class VSDKOutputTests(FunctionalTest):
    """ Tests for SwaggerParser using file option

    """
    @classmethod
    def setUpClass(cls):
        """ Set up context

        """
        os.makedirs(cls.TMP_PATH)
        generator = VSDKGenerator(vsdurl=None, path=cls.get_swagger_files_path(), apiversion=None, revision=None, output_path=cls.TMP_PATH)
        generator.run()

    @classmethod
    def tearDownClass(cls):
        """ Clean generated tests

        """
        shutil.rmtree(cls.TMP_PATH)
        pass

    def test_validate_autogenerates(self):
        """ Validates autogenerated files

        """

        self.assertFileOutputEqual('/autogenerates', 'nudomain', 'NUDomain is not correct')
        self.assertFileOutputEqual('/autogenerates', 'nuenterprise', 'NUEnterprise is not correct')
        self.assertFileOutputEqual('/autogenerates', 'nurestuser', 'NURESTUser is not correct')
        self.assertFileOutputEqual('', 'constants', 'Constants file is not correct')
        self.assertFileOutputEqual('', 'nunsgateway', 'NUNSGateway file is not correct')
