# -*- coding: utf-8 -*-

import os
import shutil

from monolithe.tests.functional import FunctionalTest
from monolithe.command import Command


class VSDKOutputTests(FunctionalTest):
    """ Tests for SwaggerParser using file option

    """
    @classmethod
    def setUpClass(cls):
        """ Set up context

        """
        os.makedirs(cls.TMP_PATH)
        Command.generate_sdk(vsdurl=None, path=cls.get_swagger_files_path(), apiversion=None, revision=None, output_path=cls.TMP_PATH)

    @classmethod
    def tearDownClass(cls):
        """ Clean generated tests

        """
        # shutil.rmtree(cls.TMP_PATH)

    def test_validate_autogenerates(self):
        """ Validates autogenerated files

        """

        self.assertFileOutputEqual('nudomain', 'NUDomain is not correct')
        # self.assertFileOutputEqual('nuenterprise', 'NUEnterprise is not correct')
        # self.assertFileOutputEqual('nurestuser', 'NURESTUser is not correct')
