{
    "attributes": [
        {
            "name": "blob",
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": false,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": null,
            "deprecated": false,
            "description": "the blob",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "orderable": true,
            "read_only": false,
            "required": false,
            "subtype": null,
            "transient": false,
            "type": "string",
            "unique": false,
            "uniqueScope": "no"
        }
    ],
    "children": [],
    "model": {
        "create": false,
        "delete": true,
        "description": null,
        "entity_name": "Metadata",
        "extends": [],
        "get": true,
        "package": null,
        "resource_name": "metadatas",
        "rest_name": "metadata",
        "root": false,
        "update": true
    }
}
