{
    "apis": {
        "children": {
            "/tasks/{id}/users": {
                "RESTName": "user",
                "entityName": "User",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "PUT"
                    }
                ],
                "relationship": "member",
                "resourceName": "users"
            }
        },
        "parents": {
            "/lists/{id}/tasks": {
                "RESTName": "list",
                "entityName": "List",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ],
                "resourceName": "lists"
            }
        },
        "self": {
            "/tasks/{id}": {
                "RESTName": "task",
                "entityName": "Task",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ],
                "resourceName": "tasks"
            }
        }
    },
    "model": {
        "RESTName": "task",
        "attributes": {
            "status": {
                "allowedChars": null,
                "allowedChoices": [
                    "TODO",
                    "DONE"
                ],
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "The status of the task",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": 2048,
                "maxValue": null,
                "minLength": 1,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "enum",
                "unique": false
            }
        },
        "description": "Represent a task to do in a list",
        "entityName": "Task",
        "extends": [
            "@description",
            "@title"
        ],
        "package": "todo-list",
        "resourceName": "tasks"
    }
}
