{
    "rest_name": "task",
    "description": "Represent a task to do in a list",
    "entity_name": "Task",
    "extends": ["@description", "@title"],
    "package": "todo-list",
    "resource_name": "tasks",
    "get": true,
    "update": true,
    "delete": true,

    "children": [
        {
            "specification": "user",
            "relationship": "member",
            "get": true,
            "update": true
        }
    ],

    "attributes": {
        "status": {
            "allowed_chars": null,
            "allowed_choices": [
                "TODO",
                "DONE"
            ],
            "autogenerated": false,
            "availability": null,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": "TODO",
            "description": "The status of the task",
            "exposed": true,
            "filterable": true,
            "format": null,
            "max_length": 2048,
            "max_value": null,
            "min_length": 1,
            "min_value": null,
            "orderable": true,
            "read_only": false,
            "required": false,
            "transient": false,
            "type": "enum",
            "unique": false
        }
    }
}
