{
  "apis": {
    "children": {
        "/tasks/{id}/users": {
          "RESTName": "user",
          "resourceName": "users",
          "entityName": "User",
          "relationship": "member",
          "operations": [
            { "availability": null, "method": "GET" },
            { "availability": null, "method": "PUT" }
          ]
        }

    },
    "parents": {
      "/lists/{id}/tasks": {
        "RESTName": "list",
        "resourceName": "lists",
        "entityName": "List",
        "operations": [
          { "availability": null, "method": "GET" },
          { "availability": null, "method": "POST" }
        ]
      }
    },
    "self": {
      "/tasks/{id}": {
        "RESTName": "task",
        "resourceName": "tasks",
        "entityName": "Task",
        "operations": [
          { "availability": null, "method": "PUT" },
          { "availability": null, "method": "DELETE" },
          { "availability": null, "method": "GET" }
        ]
      }
    }
  },
  "model": {
    "extends": ["@description", "@title"],
    "RESTName": "task",
    "description": "Represent a task to do in a list",
    "entityName": "Task",
    "package": "todo-list",
    "resourceName": "tasks",
    "attributes": {
      "status": {
        "allowedChars": null,
        "allowedChoices": ["TODO", "DONE"],
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "The status of the task",
        "exposed": true,
        "filterable": true,
        "format": null,
        "maxLength": 2048,
        "maxValue": null,
        "minLength": 1,
        "minValue": null,
        "orderable": true,
        "readOnly": false,
        "required": true,
        "transient": false,
        "type": "enum",
        "unique": false
      }
    }
  }
}